## list comprehension

- list comprehension is an elegant way to define and create listed based on exsting lists.
- list comprehension is generally more compact and faster than normal functions and loops for creating list.
- list comprehension offers a shorter syntax when you want to create a new list based on the values of an exsting list.

#### Syntax:

In [ ]:
Basic syntax -----> [expression for item in iterable]

Using if syntax -----> [expression for item in iterable if condition]

Using if else syntax ----> [expression if condition else statement for item in iterable]

### without using list comprehension

In [52]:
fruits = ['apple','banana','cherry','orange','mango']

In [53]:
fruits

['apple', 'banana', 'cherry', 'orange', 'mango']

In [54]:
new_list=[]  # create empty list

for i in fruits:
    
    if "a" in i:
        new_list.append(i) 
        
        
print(new_list)        # without using list comprehension

['apple', 'banana', 'orange', 'mango']


### using list comprehension

In [55]:
fruits

['apple', 'banana', 'cherry', 'orange', 'mango']

#### syntax:

In [ ]:
[expression for item in iterable if condition]

In [58]:
fruits

['apple', 'banana', 'cherry', 'orange', 'mango']

In [57]:
[m for m in fruits if "a" in m]

['apple', 'banana', 'orange', 'mango']

### Basic syntax -----> [expression for item in iterable]

In [59]:
l1 = [10,20,30,40,50]

l1

[10, 20, 30, 40, 50]

In [64]:
[a3 for a3 in l1]

[10, 20, 30, 40, 50]

#### example

In [60]:
for a1 in [1,2,3,4]:
    print(a1)

1
2
3
4


In [63]:
for a2 in range(2,5):
    print(a2)

2
3
4


#### Using if syntax -----> [expression for item in iterable if condition]

In [65]:
# example

[m1 for m1 in [1,2,3,4,5] if m1%2==0]

[2, 4]

#### Using if else syntax ----> [expression if condition else statement for item in iterable]

#### example

In [75]:
[x if x%2==0 else x for x in [1,2,3,4,5,6,7,8,9,10]]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [78]:
[ "even" if x1%2==0 else "odd" for x1 in [1,2,3,4,5,6,7,8,9,10]]

['odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even']

#### example

In [79]:
s={}

type(s)

dict

In [79]:
#######################################################################################

### Numpy Introduction

- NumPy is a Python library created in 2005 that performs numerical calculations. It is generally used for working with arrays.

- NumPy also includes a wide range of mathematical functions, such as linear algebra, Fourier transforms, and random number generation, which can be applied to arrays.



#### What is NumPy Used for?

- Machine Learning
- Data Science
- Image and Signal Processing
- Scientific Computing

In [1]:
import numpy as np

In [2]:
p1 = np.array(34)

In [3]:
p1

array(34)

In [101]:
type(p1)

numpy.ndarray

#### dimension check

In [4]:
np.ndim(p1)

0

### Array

In [5]:
p2 = np.array([1,2,3,4,5,6,7,8,9,10])

In [6]:
p2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### array indexing

In [7]:
p2[4]

5

In [8]:
p2[0]

1

In [9]:
x1 = np.array([[1,2,3,4,5,6,7,8,9,10],[10,20,30,40,50,60,70,80,90,10]])

In [10]:
x1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [10, 20, 30, 40, 50, 60, 70, 80, 90, 10]])

In [13]:
x1[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
x1[1]

array([10, 20, 30, 40, 50, 60, 70, 80, 90, 10])

In [15]:
x1[2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [17]:
x1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [10, 20, 30, 40, 50, 60, 70, 80, 90, 10]])

In [24]:
x1[1][5]

60

In [21]:
x1[1][5]

60

#### array slicing

In [ ]:
[start:end:step]

In [25]:
array1 = [10,20,30,40,50]

In [26]:
array1

[10, 20, 30, 40, 50]

In [27]:
array1[:]

[10, 20, 30, 40, 50]

In [28]:
array1[:3]

[10, 20, 30]

In [29]:
array1[2:]

[30, 40, 50]

In [31]:
array1[::1]

[10, 20, 30, 40, 50]

In [34]:
x2 = np.array([[1,2,3,4,5,6,7,8,9,10],[10,20,30,40,50,60,70,80,90,10],[45,37,45]],dtype=object)

In [35]:
x2

array([list([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]),
       list([10, 20, 30, 40, 50, 60, 70, 80, 90, 10]), list([45, 37, 45])],
      dtype=object)

In [62]:
x3= np.array([[1,2,3,4,5,6,7,8,9,10],[10,20,30,40,50,60,70,80,90,10],[45,37,45,34,56,67,12,78,23,89]])

In [63]:
np.ndim(x3)

2

In [39]:
x3

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [10, 20, 30, 40, 50, 60, 70, 80, 90, 10],
       [45, 37, 45, 34, 56, 67, 12, 78, 23, 89]])

In [52]:
x3[:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [10, 20, 30, 40, 50, 60, 70, 80, 90, 10],
       [45, 37, 45, 34, 56, 67, 12, 78, 23, 89]])

In [53]:
x3[0:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [10, 20, 30, 40, 50, 60, 70, 80, 90, 10],
       [45, 37, 45, 34, 56, 67, 12, 78, 23, 89]])

In [55]:
x3[1:]

array([[10, 20, 30, 40, 50, 60, 70, 80, 90, 10],
       [45, 37, 45, 34, 56, 67, 12, 78, 23, 89]])

In [56]:
x3[2:]

array([[45, 37, 45, 34, 56, 67, 12, 78, 23, 89]])

In [57]:
x3[3:]

array([], shape=(0, 10), dtype=int32)

In [64]:
x3

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [10, 20, 30, 40, 50, 60, 70, 80, 90, 10],
       [45, 37, 45, 34, 56, 67, 12, 78, 23, 89]])

In [ ]:
variable_name[index/row][column]

In [65]:
x3[0][3]

4

In [66]:
x3[2][9]

89

In [112]:
x3

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [10, 20, 30, 40, 50, 60, 70, 80, 90, 10],
       [45, 37, 45, 34, 56, 67, 12, 78, 23, 89]])

In [113]:
x3[1][7]=10

In [114]:
x3

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [10, 20, 30, 40, 50, 60, 70, 10, 90, 10],
       [45, 37, 45, 34, 56, 67, 12, 78, 23, 89]])

In [ ]:
x3[][]

In [68]:
x3

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [10, 20, 30, 40, 50, 60, 70, 80, 90, 10],
       [45, 37, 45, 34, 56, 67, 12, 78, 23, 89]])

In [70]:
x3[0:8][1:9]

array([[10, 20, 30, 40, 50, 60, 70, 80, 90, 10],
       [45, 37, 45, 34, 56, 67, 12, 78, 23, 89]])

In [78]:
x3

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [10, 20, 30, 40, 50, 60, 70, 80, 90, 10],
       [45, 37, 45, 34, 56, 67, 12, 78, 23, 89]])

In [77]:
x3[1:2, 0:2]

array([[10, 20]])

In [82]:
x3[1:2, 0:2]

array([[10, 20]])

## Array creation

- 0_D array
- 1_D array
- 2_D array
- 3_D array

### 0_D array

In [106]:
A1 =np.array(100)

A1

array(100)

#### syntax

In [ ]:
np.ndim(variable_name)

#### check array dimension

In [107]:
np.ndim(A1)  # 

0

### 1_D array

In [109]:
A2 =np.array([1,2,3,4,5])

In [110]:
A2

array([1, 2, 3, 4, 5])

In [111]:
np.ndim(A2)

1

### 2_D array

In [ ]:
A3

### 3_D array

### arange()

#### syntax:

In [92]:
A3 =np.arange(2,21,2)

A3

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### reshape()

In [94]:
A4 =np.arange(1,31).reshape(5,6)

A4

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [96]:
import random as rd

In [103]:
A6 =rd.randint(1,31).reshape(5,6)

A6

AttributeError: 'int' object has no attribute 'reshape'

In [95]:
A5 =np.arange(1,31).reshape(7,8)

A5

ValueError: cannot reshape array of size 30 into shape (7,8)

### Array creation using zeros 

### zeros()

In [130]:
# example


A5= np.zeros(5,dtype=int)

In [131]:
A5

array([0, 0, 0, 0, 0])

In [108]:
# example2

A6 = np.zeros((5,7),bool)
A6

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])

## ones

In [ ]:
syntax

In [107]:
A7 = np.ones((5,7),bool)
A7

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

## full

In [111]:
A8 =np.full((4,6),50)

A8

array([[50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50]])

In [116]:
A8[0][4]=60

In [117]:
A8

array([[50, 50, 50, 50, 60, 50],
       [50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50]])

## Random Module

- randrange()
- randint()
- choice()
- shuffle()
- sample()
- random()

### randrange()

### randint()

### choice()

- The choice() method returns a randomly selected element from the specified sequence.

- The sequence can be a string, a range, a list, a tuple or any other kind of sequence.



In [32]:
# mylist = ["apple", "banana", "cherry"]

# print(random.choice(mylist))

### shuffle()

### sample()

In [45]:
# mylist = ["apple", "banana", "cherry"]

# print(random.sample(mylist,2))

### random()

In [50]:
####################################################################################

### Arithmetic Operations in Numpy

- add()
- subtract()
- multiply()
- divide()


In [49]:
import random
import numpy as np

In [50]:
np.random.seed(763458346586485793745937654656545645648484)
random.randint(1,10)


ValueError: Seed must be between 0 and 2**32 - 1

In [8]:
for i in range(1,11):
    random.seed(10)
    print(i)

1
2
3
4
5
6
7
8
9
10
