# Numpy:

- Random Module
- Arithmetic Operations in Numpy
- Functions in Numpy : Sum, Mean, Std, Var, exp, log, sqrt, etc
- Where and ABS function
- Concatenate
- Stacking 
- Splitting

## Random Module

- randrange()
- randint()
- choice()
- shuffle()
- sample()
- random()

### randrange()

#### syntax

#### example

In [120]:
import numpy as np
import random                    #import random module to generate random numbers

In [128]:
v2 =random.randrange(5)   # return 0,1,2,3,4

v2

2

### randint()

In [ ]:
The randint() method returns an integer number selected element from the specified range.

#### syntax

In [ ]:
random.randint(start,end)   #start and end both necessary

In [150]:
v3 =random.randint(0,5)   # return 0,1,2,3,4,5
                         #start and end both include

v3

2

### choice()

- The choice() method returns a randomly selected element from the specified sequence.

- The sequence can be a string, a range, a list, a tuple or any other kind of sequence.

In [153]:
mylist = ["apple", "banana", "cherry"]

print(random.choice(mylist))      # Returns a random element from mylist

cherry


### shuffle()

In [155]:
m2 = ["apple", "banana", "cherry"]

random.shuffle(m2)         # Shuffles the elements in m2 randomly

m2

['banana', 'cherry', 'apple']

### sample()

In [158]:
m5 = ["apple", "banana", "cherry","abc","xyz"]

print(random.sample(m5,3))     # Returns a list with 2 randomly selected elements from m5


['cherry', 'xyz', 'abc']


### random()

#### syntax

#### example

In [160]:
print(random.random())       # Returns a random floating-point number between 0 and 1


0.6147999250137957


In [38]:
#################################################################################

### Arithmetic Operations in Numpy

- add()
- subtract()
- multiply()
- divide()


### add()

In [167]:
s1 =np.array([1,2,3,4,5])

s2 =np.array([6,7,8,9,10])

In [168]:
c = np.add(s1,s2)            # Element-wise addition of s1 and s2

c

array([ 7,  9, 11, 13, 15])

### subtract()

In [115]:
v1 =np.array([10,20,30,40,50])

v2 =np.array([6,7,8,9,10])


c1 = np.subtract(v1,v2)            # Element-wise subtraction of v1 and v2

c1



array([ 4, 13, 22, 31, 40])

### multiply()

### divide()

In [ ]:
                     #######################################################

### Functions in Numpy :

- sum
- mean(avg)
- std
- var
- exp
- log
- sqrt

### example

In [169]:
d1 = np.array([1,2,3,4,5])

d1

array([1, 2, 3, 4, 5])

#### sum

In [43]:
np.sum(d1)      # Calculates the sum of elements in d1

15

In [170]:
###################################################################################

### where()

#### syntax:

In [ ]:
np.where(condition,x,y)

#### example

In [1]:
t1 =np.array([1,2,3,4,5])

t2 =np.array([6,7,8,9,10])

# z = np.where((t1>2),t1,t2)  # Selects elements from t1 where the condition is True, otherwise from t2

# z

k1=(t1>2)
# k1

NameError: name 'np' is not defined

### abs()

In [ ]:
abs --> return absolute value(positive value)

In [89]:
np.abs(-10)              # Returns the absolute value of -10


10

In [90]:
h = np.array([10,-55,66])

h

array([ 10, -55,  66])

In [92]:
np.abs(h)

array([10, 55, 66])

### concatenate()

In [174]:
A=np.array([1,2,3])
B=np.array([4,1,5])

In [175]:
w =np.concatenate((A,B))          # Concatenates arrays A and B

w

array([1, 2, 3, 4, 1, 5])

### stack


In [176]:
A

array([1, 2, 3])

In [177]:
B

array([4, 1, 5])

In [182]:
q=np.stack((A,B),axis=1)
                           # Stacks arrays A and B along the specified axis
q

array([[1, 4],
       [2, 1],
       [3, 5]])

In [73]:
np.ndim(q)     # dimension check

2

### split

In [186]:

arr = np.array([1, 2, 3, 4, 5, 6,7,8,9,10]) # Create an array of numbers from 1 to 10

newarr = np.split(arr, 2)    # Split the array 'arr' into 5 roughly equal parts

print(newarr)               # Each sub-array represents a split segment


[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]


In [118]:

# example2


arr1 = np.array([1, 2, 3, 4, 5, 6,7,8,9,10])

newarr1 = np.split(arr1, 6)  #'arr1' cannot be divided evenly into 6 segments

print(newarr1)

# Attempt to split 'arr1' into 6 roughly equal parts
# However, this attempt will result in an error due to unequal division


# Now let's use 'array_split' instead

ValueError: array split does not result in an equal division

## array_split()

In [188]:
a1 = np.array([1, 2, 3, 4, 5, 6,7,8,9,10])

new1 = np.array_split(a1, 3)  # Use 'array_split' to split 'a1' into 6 roughly equal parts

print(new1)

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]


# Pandas

#### import library

## rename

#### rename index

#### column rename

### replace

### indexing

### iloc

#### Selecting rows using integer indices

In [2]:
# df.iloc[[13,2,6,8,11,10]]

#### Selecting a range of columns and rows simultaneously

In [ ]:
df.iloc[0: 5, 2: 4]     #iloc[index,columns]   [index=start:end-1,columns=start:end-1]

#df.iloc[:,[0,3,4]]

In [ ]:
# df.iloc[:,[0,3,4]]

### loc

In [3]:
# df1.loc[[5,10,7],['Id','salary','gender']]

# df1.loc[(df1.salary>=60000)]

# df1.loc[(df1.salary>=60000) & (df1.gender=='F') & (df1.city=='nagpur') ]

### duplicated()

### drop_duplicates()

In [34]:
import pandas as pd

# Create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 22, 35],
        'Salary': [50000, 60000, 45000, 70000]}

df = pd.DataFrame(data)

# Sort the DataFrame by a specific column (e.g., 'Age') in ascending order
sorted_df = df.sort_values(by='Age', ascending=False)

# To sort in descending order, you can specify the 'ascending' parameter as False
# sorted_df = df.sort_values(by='Age', ascending=False)

# Display the sorted DataFrame
print(sorted_df)


      Name  Age  Salary
3    David   35   70000
1      Bob   30   60000
0    Alice   25   50000
2  Charlie   22   45000


In [35]:
import pandas as pd

In [36]:
df1=pd.read_csv(r'C:\Users\Acer\Downloads\world_data_2023.csv')

df1

Country Density\n(P/Km2) Abbreviation Agricultural Land( %)  \
0    Afghanistan               60           AF                58.10%   
1        Albania              105           AL                43.10%   
2        Algeria               18           DZ                17.40%   
3        Andorra              164           AD                40.00%   
4         Angola               26           AO                47.50%   
..           ...              ...          ...                   ...   
190    Venezuela               32           VE                24.50%   
191      Vietnam              314           VN                39.30%   
192        Yemen               56           YE                44.60%   
193       Zambia               25           ZM                32.10%   
194     Zimbabwe               38           ZW                41.90%   

    Land Area(Km2) Armed Forces size  Birth Rate  Calling Code  \
0          652,230           323,000       32.49          93.0   
1           28,748             9,000       11.78         355.0   
2        2,381,741           317,000       24.28         213.0   
3              468               NaN        7.20         376.0   
4        1,246,700           117,000       40.73         244.0   
..             ...               ...         ...           ...   
190        912,050           343,000       17.88          58.0   
191        331,210           522,000       16.75          84.0   
192        527,968            40,000       30.45         967.0   
193        752,618            16,000       36.19         260.0   
194        390,757            51,000       30.68         263.0   

    Capital/Major City Co2-Emissions  ... Out of pocket health expenditure  \
0                Kabul         8,672  ...                           78.40%   
1               Tirana         4,536  ...                           56.90%   
2              Algiers       150,006  ...                           28.10%   
3     Andorra la Vella           469  ...                           36.40%   
4               Luanda        34,693  ...                           33.40%   
..                 ...           ...  ...                              ...   
190            Caracas       164,175  ...                           45.80%   
191              Hanoi       192,668  ...                           43.50%   
192              Sanaa        10,609  ...                           81.00%   
193             Lusaka         5,141  ...                           27.50%   
194             Harare        10,983  ...                           25.80%   

    Physicians per thousand  Population  \
0                      0.28  38,041,754   
1                      1.20   2,854,191   
2                      1.72  43,053,054   
3                      3.33      77,142   
4                      0.21  31,825,295   
..                      ...         ...   
190                    1.92  28,515,829   
191                    0.82  96,462,106   
192                    0.31  29,161,922   
193                    1.19  17,861,030   
194                    0.21  14,645,468   

     Population: Labor force participation (%) Tax revenue (%) Total tax rate  \
0                                       48.90%           9.30%         71.40%   
1                                       55.70%          18.60%         36.60%   
2                                       41.20%          37.20%         66.10%   
3                                          NaN             NaN            NaN   
4                                       77.50%           9.20%         49.10%   
..                                         ...             ...            ...   
190                                     59.70%             NaN         73.30%   
191                                     77.40%          19.10%         37.60%   
192                                     38.00%             NaN         26.60%   
193                                     74.60%          16.20%         15.60%   
194   

In [37]:
df1.head()

Country Density\n(P/Km2) Abbreviation Agricultural Land( %)  \
0  Afghanistan               60           AF                58.10%   
1      Albania              105           AL                43.10%   
2      Algeria               18           DZ                17.40%   
3      Andorra              164           AD                40.00%   
4       Angola               26           AO                47.50%   

  Land Area(Km2) Armed Forces size  Birth Rate  Calling Code  \
0        652,230           323,000       32.49          93.0   
1         28,748             9,000       11.78         355.0   
2      2,381,741           317,000       24.28         213.0   
3            468               NaN        7.20         376.0   
4      1,246,700           117,000       40.73         244.0   

  Capital/Major City Co2-Emissions  ... Out of pocket health expenditure  \
0              Kabul         8,672  ...                           78.40%   
1             Tirana         4,536  ...                           56.90%   
2            Algiers       150,006  ...                           28.10%   
3   Andorra la Vella           469  ...                           36.40%   
4             Luanda        34,693  ...                           33.40%   

  Physicians per thousand  Population  \
0                    0.28  38,041,754   
1                    1.20   2,854,191   
2                    1.72  43,053,054   
3                    3.33      77,142   
4                    0.21  31,825,295   

   Population: Labor force participation (%) Tax revenue (%) Total tax rate  \
0                                     48.90%           9.30%         71.40%   
1                                     55.70%          18.60%         36.60%   
2                                     41.20%          37.20%         66.10%   
3                                        NaN             NaN            NaN   
4                                     77.50%           9.20%         49.10%   

  Unemployment rate Urban_population   Latitude  Longitude  
0            11.12%        9,797,273  33.939110  67.709953  
1            12.33%        1,747,593  41.153332  20.168331  
2            11.70%       31,510,100  28.033886   1.659626  
3               NaN           67,873  42.506285   1.521801  
4             6.89%       21,061,025 -11.202692  17.873887  

[5 rows x 35 columns]

In [23]:
t1=df1.sort_values(by='Agricultural Land( %)', ascending=False)

t1

Country Density\n(P/Km2) Abbreviation  \
187                         Uruguay               20           UY   
151                    Saudi Arabia               16           SA   
87                       Kazakhstan                7           KZ   
97                            Libya                4           LY   
71                           Guyana                4           GY   
..                              ...              ...          ...   
113                          Monaco           26,337           MC   
120                           Nauru              541           NR   
128                 North Macedonia               83          NaN   
133  Palestinian National Authority              847          NaN   
163                     South Sudan               18           SS   

    Agricultural Land( %) Land Area(Km2) Armed Forces size  Birth Rate  \
187                82.60%        176,215            22,000       13.86   
151                80.80%      2,149,690           252,000       17.80   
87                 80.40%      2,724,900            71,000       21.77   
97                  8.70%      1,759,540                 0       18.83   
71                  8.60%        214,969             3,000       19.97   
..                    ...            ...               ...         ...   
113                   NaN              2               NaN        5.90   
120                   NaN             21               NaN         NaN   
128                   NaN         25,713               NaN         NaN   
133                   NaN            NaN               NaN         NaN   
163                   NaN        644,329           185,000       35.01   

     Calling Code  Capital/Major City Co2-Emissions  ...  \
187         598.0          Montevideo         6,766  ...   
151         966.0              Riyadh       563,449  ...   
87            7.0              Astana       247,207  ...   
97          218.0                 NaN        50,564  ...   
71          592.0  Georgetown, Guyana         2,384  ...   
..            ...                 ...           ...  ...   
113         377.0         Monaco City           NaN  ...   
120         674.0      Yaren District           NaN  ...   
128         389.0              Skopje           NaN  ...   
133           NaN                 NaN           NaN  ...   
163         211.0                Juba         1,727  ...   

    Out of pocket health expenditure Physicians per thousand  Population  \
187                           16.20%                    5.05   3,461,734   
151                           15.00%                    2.61  34,268,528   
87                            38.80%                    3.25  18,513,930   
97                            36.70%                    2.09   6,777,452   
71                            40.50%                    0.80     782,766   
..                               ...                     ...         ...   
113                            6.10%                    6.56      38,964   
120                              NaN                     NaN      10,084   
128                           35.60%                     NaN   1,836,713   
133                              NaN                     NaN         NaN   
163                           61.30%                     NaN  11,062,113   

     Population: Labor force participation (%) Tax revenue (%) Total tax rate  \
187                                     64.00%          20.10%         41.80%   
151                                     55.90%           8.90%         15.70%   
87                                      68.80%          11.70%         28.40%   
97                                      49.70%             NaN         32.60%   
71                                      56.20%             NaN         30.60%   
..                                         ...             ...            ...   
113                                        NaN             NaN            NaN   
120                         

In [24]:
t1.head(20)

Country Density\n(P/Km2) Abbreviation  \
187                   Uruguay               20           UY   
151              Saudi Arabia               16           SA   
87                 Kazakhstan                7           KZ   
97                      Libya                4           LY   
71                     Guyana                4           GY   
90                     Kuwait              240           KW   
33   Central African Republic                8           CF   
161              South Africa               49           ZA   
27                    Burundi              463           BI   
126                   Nigeria              226           NG   
95                    Lesotho               71           LS   
52                El Salvador              313           SV   
170                     Syria               95           SY   
54                    Eritrea               35           ER   
112                   Moldova              123           MD   
144                    Rwanda              525           RW   
47                   Djibouti               43           DJ   
180              Turkmenistan               13           TM   
182                    Uganda              229           UG   
183                   Ukraine               75           UA   

    Agricultural Land( %) Land Area(Km2) Armed Forces size  Birth Rate  \
187                82.60%        176,215            22,000       13.86   
151                80.80%      2,149,690           252,000       17.80   
87                 80.40%      2,724,900            71,000       21.77   
97                  8.70%      1,759,540                 0       18.83   
71                  8.60%        214,969             3,000       19.97   
90                  8.40%         17,818            25,000       13.94   
33                  8.20%        622,984             8,000       35.35   
161                79.80%      1,219,090            80,000       20.51   
27                 79.20%         27,830            31,000       39.01   
126                77.70%        923,768           215,000       37.91   
95                 77.60%         30,355             2,000       26.81   
52                 76.40%         21,041            42,000       18.25   
170                75.80%        185,180           239,000       23.69   
54                 75.20%        117,600           202,000       30.30   
112                74.20%         33,851             7,000       10.10   
144                73.40%         26,338            35,000       31.70   
47                 73.40%         23,200            13,000       21.47   
180                72.00%        488,100            42,000       23.83   
182                71.90%        241,038            46,000       38.14   
183                71.70%        603,550           297,000        8.70   

     Calling Code  Capital/Major City Co2-Emissions  ...  \
187         598.0          Montevideo         6,766  ...   
151         966.0              Riyadh       563,449  ...   
87            7.0              Astana       247,207  ...   
97          218.0                 NaN        50,564  ...   
71          592.0  Georgetown, Guyana         2,384  ...   
90          965.0         Kuwait City        98,734  ...   
33          236.0              Bangui           297  ...   
161          27.0            Pretoria       476,644  ...   
27          257.0           Bujumbura           495  ...   
126         234.0               Abuja       120,369  ...   
95          266.0              Maseru         2,512  ...   
52          503.0        San Salvador         7,169  ...   
170         963.0            Damascus        28,830  ...   
54          291.0              Asmara           711  ...   
112         373.0             Chi����         5,115  ...   
144         250.0              Kigali         1,115  ...   
47          253.0       Djibouti City           620  ...   
180         993.0            Ashgabat        70,630  ...   
182

In [25]:
df1.columns

Index(['Country', 'Density\n(P/Km2)', 'Abbreviation', 'Agricultural Land( %)',
       'Land Area(Km2)', 'Armed Forces size', 'Birth Rate', 'Calling Code',
       'Capital/Major City', 'Co2-Emissions', 'CPI', 'CPI Change (%)',
       'Currency-Code', 'Fertility Rate', 'Forested Area (%)',
       'Gasoline Price', 'GDP', 'Gross primary education enrollment (%)',
       'Gross tertiary education enrollment (%)', 'Infant mortality',
       'Largest city', 'Life expectancy', 'Maternal mortality ratio',
       'Minimum wage', 'Official language', 'Out of pocket health expenditure',
       'Physicians per thousand', 'Population',
       'Population: Labor force participation (%)', 'Tax revenue (%)',
       'Total tax rate', 'Unemployment rate', 'Urban_population', 'Latitude',
       'Longitude'],
      dtype='object')

In [26]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 35 columns):
 #   Column                                     Non-Null Count  Dtype  
---  ------                                     --------------  -----  
 0   Country                                    195 non-null    object 
 1   Density
(P/Km2)                            195 non-null    object 
 2   Abbreviation                               188 non-null    object 
 3   Agricultural Land( %)                      188 non-null    object 
 4   Land Area(Km2)                             194 non-null    object 
 5   Armed Forces size                          171 non-null    object 
 6   Birth Rate                                 189 non-null    float64
 7   Calling Code                               194 non-null    float64
 8   Capital/Major City                         192 non-null    object 
 9   Co2-Emissions                              188 non-null    object 
 10  CPI                       

In [32]:
df1['Agricultural Land( %)']=pd.to_numeric(df1['Agricultural Land( %)'], errors='coerce', downcast='integer')

In [33]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 35 columns):
 #   Column                                     Non-Null Count  Dtype  
---  ------                                     --------------  -----  
 0   Country                                    195 non-null    object 
 1   Density
(P/Km2)                            195 non-null    object 
 2   Abbreviation                               188 non-null    object 
 3   Agricultural Land( %)                      0 non-null      float64
 4   Land Area(Km2)                             194 non-null    object 
 5   Armed Forces size                          171 non-null    object 
 6   Birth Rate                                 189 non-null    float64
 7   Calling Code                               194 non-null    float64
 8   Capital/Major City                         192 non-null    object 
 9   Co2-Emissions                              188 non-null    object 
 10  CPI                       

In [19]:
import pandas as pd

# Sample DataFrame
data = {'Column1': ['1', '2', '3', '4']}
df = pd.DataFrame(data)

# Convert 'Column1' to integer
df['Column1'] = pd.to_numeric(df['Column1'], errors='coerce', downcast='integer')

# Check the data types
print(df.dtypes)


Column1    int8
dtype: object


In [38]:
df1.info(memory_usage='deep')


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 35 columns):
 #   Column                                     Non-Null Count  Dtype  
---  ------                                     --------------  -----  
 0   Country                                    195 non-null    object 
 1   Density
(P/Km2)                            195 non-null    object 
 2   Abbreviation                               188 non-null    object 
 3   Agricultural Land( %)                      188 non-null    object 
 4   Land Area(Km2)                             194 non-null    object 
 5   Armed Forces size                          171 non-null    object 
 6   Birth Rate                                 189 non-null    float64
 7   Calling Code                               194 non-null    float64
 8   Capital/Major City                         192 non-null    object 
 9   Co2-Emissions                              188 non-null    object 
 10  CPI                       

In [40]:
df1.to_excel('C:\Users\Acer\Downloads\world_data_2023.csv')

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (3909121369.py, line 1)

In [ ]:
file read
head
tail
info
describe
unique
null_value chack
fill missing value
sorting
univariate analysis
bivariate analysis
multivariate analysis